# Unix submit description file
# Ignition_Delay.sub -- python job

executable              = Ignition_Delay.sh
arugments               = $(ProcId)
log                     = log/Ignition_Delay_$(ProcId).log
output                  = out/Ignition_Delay_$(ProcId).out
error                   = err/Ignition_Delay_$(ProcId).err
transfer_input_files    = Ignition_Delay_Temp_ALG.py, RenKokjohn.cti 
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT

queue 30
